name: Print Message ASAP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install figlet
      run: sudo apt-get install -y figlet

    - name: Print message using figlet
      run: figlet "Shreya is beautiful"
